"""PDF rendering for an audit report.

Auditors hand reports to clients, and a client does not want a terminal dump. This renders
the same result object the markdown report is built from, so the two cannot drift: there is
no second source of truth, only a second layout.

reportlab is optional and pure Python, no system libraries. Without it, `--format pdf`
fails loudly rather than silently writing nothing, which is the same contract the rest of
the tool follows for a missing dependency.
"""

from __future__ import annotations

from datetime import UTC, datetime
from html import escape
from pathlib import Path

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

# Print-safe. These are read on paper and on a projector, not only on a bright screen.
SEVERITY_COLOR = {
    "critical": "#8B0000",
    "high": "#B54708",
    "medium": "#7A5B00",
    "low": "#31506B",
    "info": "#4A4A4A",
}


class PdfUnavailable(RuntimeError):
    """reportlab is not installed. The caller reports it rather than writing an empty file."""


def _require():
    try:
        from reportlab.lib import colors  # noqa: F401
        from reportlab.lib.enums import TA_LEFT  # noqa: F401
    except ImportError as exc:
        raise PdfUnavailable(
            "PDF output needs reportlab: pip install reportlab"
        ) from exc


def _styles():
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm

    s = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=s["Title"], fontSize=22, spaceAfter=2 * mm,
                                alignment=TA_LEFT, fontName="Helvetica-Bold"),
        "sub": ParagraphStyle("sub", parent=s["Normal"], fontSize=9.5, textColor="#555555",
                              spaceAfter=1.5 * mm, fontName="Helvetica"),
        "h2": ParagraphStyle("h2", parent=s["Heading2"], fontSize=14, spaceBefore=7 * mm,
                             spaceAfter=2.5 * mm, fontName="Helvetica-Bold"),
        "finding": ParagraphStyle("f", parent=s["Heading3"], fontSize=11, spaceBefore=5 * mm,
                                  spaceAfter=1 * mm, fontName="Helvetica-Bold"),
        "meta": ParagraphStyle("m", parent=s["Normal"], fontSize=8, textColor="#666666",
                               fontName="Courier", spaceAfter=1.5 * mm),
        "body": ParagraphStyle("b", parent=s["Normal"], fontSize=9.5, leading=13.5,
                               spaceAfter=1.5 * mm),
        "code": ParagraphStyle("c", parent=s["Code"], fontSize=8, leading=10.5,
                               textColor="#1a1a1a", backColor="#F4F4F4",
                               borderPadding=5, leftIndent=2, spaceAfter=2 * mm),
        "note": ParagraphStyle("n", parent=s["Normal"], fontSize=9, leading=12.5,
                               textColor="#333333", spaceAfter=1.5 * mm, leftIndent=4 * mm),
    }


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor("#888888")
    canvas.drawString(18 * 2.83465, 12 * 2.83465, "Generated by rootward")
    canvas.drawRightString(doc.pagesize[0] - 18 * 2.83465, 12 * 2.83465, f"page {doc.page}")
    canvas.restoreState()


def _wrap_code(text: str, width: int = 96) -> str:
    """Hard-wrap evidence so a long minified line cannot run off the page."""
    out = []
    for line in (text or "").splitlines() or [""]:
        while len(line) > width:
            out.append(line[:width])
            line = line[width:]
        out.append(line)
    return escape("\n".join(out)) or "&nbsp;"


def render_pdf(result: dict, out_path: Path, catalog: dict | None = None) -> Path:
    """Write the report to `out_path` and return it."""
    _require()
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Table,
        TableStyle,
    )

    st = _styles()
    findings = result.get("findings", [])
    counts = {s: sum(1 for f in findings if f["severity"] == s) for s in SEVERITY_ORDER}
    counts = {k: v for k, v in counts.items() if v}
    sc = result.get("scorecard") or {}

    doc = SimpleDocTemplate(
        str(out_path), pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=18 * mm,
        title="rootward audit report", author="rootward",
    )
    story = []

    story.append(Paragraph("rootward audit report", st["title"]))
    story.append(Paragraph(
        f"{escape(str(result.get('root','')))}<br/>"
        f"Platform detected: {escape(str(result.get('platform',{}).get('summary','unknown')))}<br/>"
        f"Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        st["sub"]))
    story.append(HRFlowable(width="100%", color="#DDDDDD", spaceBefore=3 * mm, spaceAfter=4 * mm))

    summary = ", ".join(f"{n} {s}" for s, n in counts.items()) or "none"
    story.append(Paragraph(f"<b>{len(findings)} findings</b> ({summary})", st["body"]))

    # --- scorecard -------------------------------------------------------------------
    story.append(Paragraph("1. Layer scorecard", st["h2"]))
    layer, ceiling = sc.get("effective_layer"), sc.get("verifiable_ceiling")
    story.append(Paragraph(
        f"Effective layer <b>{layer if layer is not None else 'not scored'}</b> "
        f"of a verifiable ceiling of {ceiling}.", st["body"]))
    # per_layer is keyed by layer number, and the status wording is copied from the
    # markdown report deliberately: two layouts of one result must not disagree about
    # whether a layer passed.
    per_layer = sc.get("per_layer") or {}
    scored = sc.get("assessed", True)
    if per_layer:
        rows = [["Layer", "Required rules", "Status"]]
        for level in range(1, 7):
            info = per_layer.get(str(level)) or per_layer.get(level)
            if not info:
                continue
            if not scored:
                status = "not assessed (no platform detected)"
            elif info["required_rules"] == 0:
                status = "unassessed (no rules)"
            elif info["passes"]:
                status = "pass"
            else:
                status = f"fails ({len(info['failing'])})"
            rows.append([str(level), str(info["required_rules"]), status])
        if len(rows) > 1:
            t = Table(rows, colWidths=[22 * mm, 34 * mm, 60 * mm], hAlign="LEFT")
            t.setStyle(TableStyle([
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8.5),
                ("FONT", (0, 1), (-1, -1), "Helvetica", 8.5),
                ("TEXTCOLOR", (0, 0), (-1, 0), "#333333"),
                ("LINEBELOW", (0, 0), (-1, 0), 0.6, "#CCCCCC"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), ["#FFFFFF", "#FAFAFA"]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(t)
    for rid in sc.get("blocking_rules") or []:
        story.append(Paragraph(f"Capped by <font face='Courier'>{escape(str(rid))}</font>", st["note"]))

    # --- findings --------------------------------------------------------------------
    story.append(Paragraph("2. Findings", st["h2"]))
    if not findings:
        story.append(Paragraph("No findings at or above the reporting threshold.", st["body"]))
    order = {s: i for i, s in enumerate(SEVERITY_ORDER)}
    for f in sorted(findings, key=lambda x: (order.get(x["severity"], 9), x["file"], x["line"])):
        colour = SEVERITY_COLOR.get(f["severity"], "#000000")
        story.append(Paragraph(
            f"<font color='{colour}'>{escape(f['severity'].upper())}</font>"
            f" &nbsp;<font face='Courier'>{escape(f['rule_id'])}</font>", st["finding"]))
        bits = [f"{f['file']}:{f['line']}", f"confidence {f.get('confidence','')}"]
        if f.get("detector"):
            bits.append(str(f["detector"]))
        if f.get("verdict"):
            bits.append(str(f["verdict"]))
        story.append(Paragraph(escape(" | ".join(bits)), st["meta"]))
        if (f.get("evidence") or "").strip():
            story.append(Paragraph(_wrap_code(f["evidence"]), st["code"]))
        story.append(Paragraph(escape(f.get("message", "")), st["body"]))

    # --- not verified ----------------------------------------------------------------
    story.append(PageBreak())
    story.append(Paragraph("3. Not verified", st["h2"]))
    story.append(Paragraph(
        "What this audit structurally could not check. A clean report above does not cover "
        "anything in this list.", st["body"]))
    for item in result.get("not_verified") or []:
        story.append(Paragraph(f"• {escape(str(item))}", st["note"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return out_path
